[build]
  publish = "dist"
  command = "npm install --legacy-peer-deps && npm run build"

# Handle SPA routing - exclude assets, API routes, and static files
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"
  # Ensure devDependencies are installed on Netlify
  NPM_CONFIG_PRODUCTION = "false"
  # Disable Husky in CI to avoid prepare hook errors
  HUSKY = "0"
  # Allow expected Supabase environment variables in build output
  SECRETS_SCAN_OMIT_KEYS = "VITE_SUPABASE_URL,VITE_SUPABASE_ANON_KEY,VITE_SUPABASE_SERVICE_ROLE_KEY"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Ensure proper MIME types for JavaScript modules with shorter cache times
[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    Cache-Control = "public, max-age=3600, immutable"

[[headers]]
  for = "/assets/*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"
    Cache-Control = "public, max-age=86400, immutable"

[[headers]]
  for = "/assets/*.woff2"
  [headers.values]
    Content-Type = "font/woff2"
    Cache-Control = "public, max-age=604800, immutable"

[[headers]]
  for = "/assets/*.woff"
  [headers.values]
    Content-Type = "font/woff"
    Cache-Control = "public, max-age=604800, immutable"

# Cache HTML files for shorter time to allow updates
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# Cache service worker with no-cache to ensure updates
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Service-Worker-Allowed = "/"